service: starbooks

provider:
  name: aws
  region: ap-northeast-1 # デプロイする AWS地域 (us-east-1 がデフォルト)
  stage: dev # アプリケーションの段階 dev、production、staging… ('dev' がデフォルト)
  runtime: provided.al2
  lambdaHashingVersion: 20201221

package:
  patterns: # デプロイから除外するディレクトリ
    - "!node_modules/**"
    - "!public/storage"
    - "!resources/assets/**"
    - "!storage/**"
    - "!tests/**"

functions:
  web: # この関数は、Laravel Webサイト/API を実行します
    handler: public/index.php # HTTP 要求が着信したときに呼び出されるファイル
    timeout: 28 # 秒単位 (API Gateway のタイムアウトは 29 秒)
    layers:
      - ${bref:layer.php-82-fpm}
    events:
      - httpApi: "*"
  # この関数により、Lambdaでartisanコマンドを実行できます
  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-82} # PHP
      - ${bref:layer.console} # The "console" layer

plugins:
  - ./vendor/bref/bref # Bref プラグインを含める必要があります

resources:
    Resources:
        MyBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: 'starbooks-bucket'